name: build-test
on:
  push:
jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
        
      - name: Docker Install
        run: |
            if ! command -v docker >/dev/null 2>&1; then
              echo "Docker not found. Installing..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            else
              echo "Docker is already installed."
            fi
            docker --version
            
      - name: create Docker Image
        run: docker build -t leo-image /
        
      - name: Container Starten
        run: echo "Hi"
        
      - name: Ausgabe
        run: echo "Jo"
